### ISSUE TITLE
[BUG] Removing trees is cosmetic only

### ISSUE THREAD

**Issue by gSe7eN** [loki79uk/FS22_LumberJack#4] opened 2022-05-01 16:11 UTC
I used this mod to clear trees by waiting for the chainsaw indicator circle to turn red. Using the chainsaw will cause the tree to disappear. However, the tree is not actually removed but rather just made invisible.

You can test this by trying to change the elevation of the land where the tree is. Removing the tree the traditional way by cutting it down and then removing the stump with a machine allows the land to be changed. Unfortunately, if you use this mod to quickly remove the tree, it's impossible to cause the tree to not exist in ghost form.

Is there a fix for this in the meantime while you fix the mod? I don't see where original map trees are stored in the save game folder, only manually planted trees.

**Comment by loki79uk** [comment] 2022-05-01 16:19
I've been trying to find a permanent fix for this since FS19, but have given up now.  As a workaround you can either cut down the tree, then delete the stump and tree separately OR you can delete the tree directly, save the game and reload.  Either of those should work as expected.

**Comment by gSe7eN** [comment] 2022-05-01 16:22
Is there anything that can be done about about the trees I've already, for lack of a better term, ghosted? I'm not afraid to dive in and get my hands dirty editing the files directly IF only I knew where to look. I can't find them anywhere.

In the future, I'll be sure to do as you say so thank you for confirming that part.

**Comment by loki79uk** [comment] 2022-05-03 21:34
It should be fine if you just save the game and reload.  Once all of the trees are reloaded from the savegame, the deleted trees should not be in the far distance (LOD) view anymore.   HOWEVER, I've actually spent some time on this over the last few days and now have a fix working in single player.  Still need to rewrite and test for multiplayer, but thanks for reminding me about it! :D

**Comment by gSe7eN** [comment] 2022-05-03 21:55
That's really great news! I found that quitting and restarting the game does NOT fix the issue. (I did notice the LOD effect at first. It didn't bother me since I'm not a detailed oriented person, it was the terrain that was really messing up my plans). I did find a work around but it's not ideal. Removing a file in the saved game (I forget what one, but it's not a simple plain text file) restored all the default trees for the map. It took a LOT of time and work, but I was able to remove those tree properly and flatten or raise the terrain.

I'm really glad you found a solution to the bug, this is a great mod!

**Comment by loki79uk** [comment] 2022-05-10 10:30
Please let me know if this version has resolved the issue:  https://github.com/loki79uk/FS22_LumberJack/releases/tag/v1.1.1.0-beta

I guess it will not do anything to your terrain issue caused by previously removed trees, but hopefully should prevent the problem occuring again.

**Closed as completed** 2022-06-24 08:32 UTC
